### ISSUE TITLE
Incorrect warning: "Warning you are running on MacOS without the JVM argument -XstartOnFirstThread, which will probably cause the OS to kill your app."

### ISSUE THREAD

**Issue by RefuX** [knokko/vk-boiler#2]
Using Oracle Version 20.
Looks like `ManagementFactory.getRuntimeMXBean().getInputArguments()` no longer includes this argument. So the `.contains("-XstartOnFirstThread")` test fails.

I fiddled around a bit with all the ways to get data off the RuntimeMXBean and couldn't find anyway to find the information.

I think this is redundant logic since GLFW gives a very clear exception:
`Exception in thread "main" java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
`

**Comment by knokko** [comment]
Hm... I guess my check is broken indeed (although I can't verify it myself since the only Macs at 'my disposal' are headless Github runners). I could fix the check using the same trick that LWJGL uses: https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/glfw/src/main/java/org/lwjgl/glfw/EventLoop.java

But... since LWJGL already does the work... I will just remove it in the next release.

**Comment by knokko** [comment]
This should be fixed in v3.1.2.
